In [1]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.2.0.tar.gz (281.3 MB)
     |████████████████████████████████| 281.3 MB 34 kB/s
Collecting py4j==0.10.9.2
  Downloading py4j-0.10.9.2-py2.py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 61.9 MB/s
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.2.0-py2.py3-none-any.whl size=281805912 sha256=bd802d8cc1d2a67612fdf6f07a8d7a8951cb5ae28bfd0c9f0f650688bb134fee
  Stored in directory: /root/.cache/pip/wheels/0b/de/d2/9be5d59d7331c6c2a7c1b6d1a4f463ce107332b1ecd4e80718
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.2 pyspark-3.2.0

In [2]:
!wget http://www.jeuxdemots.org/JDM-LEXICALNET-FR/09032019-LEXICALNET-JEUXDEMOTS-FR-NOHTML.txt.zip
!unzip 09032019-LEXICALNET-JEUXDEMOTS-FR-NOHTML.txt.zip  -d ./
!iconv -f CP1252 -t UTF-8 /content/JDM-LEXICALNET-FR/09032019-LEXICALNET-JEUXDEMOTS-FR-NOHTML.txt -o /content/JDM-LEXICALNET-FR/09032019-LEXICALNET-JEUXDEMOTS-FR-NOHTML-UTF8.txt

--2021-10-21 13:02:27--  http://www.jeuxdemots.org/JDM-LEXICALNET-FR/09032019-LEXICALNET-JEUXDEMOTS-FR-NOHTML.txt.zip
Resolving www.jeuxdemots.org (www.jeuxdemots.org)... 193.49.110.106
Connecting to www.jeuxdemots.org (www.jeuxdemots.org)|193.49.110.106|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1930689580 (1.8G) [application/zip]
Saving to: ‘09032019-LEXICALNET-JEUXDEMOTS-FR-NOHTML.txt.zip’

09032019-LEXICALNET 100%[===================>]   1.80G  29.4MB/s    in 65s

2021-10-21 13:03:31 (28.5 MB/s) - ‘09032019-LEXICALNET-JEUXDEMOTS-FR-NOHTML.txt.zip’ saved [1930689580/1930689580]

Archive:  09032019-LEXICALNET-JEUXDEMOTS-FR-NOHTML.txt.zip
  inflating: ./JDM-LEXICALNET-FR/09032019-LEXICALNET-JEUXDEMOTS-FR-NOHTML.txt

In [3]:
import sys
import os
import pyspark as ps
import warnings
import re
import datetime

from pyspark import SparkContext 
from pyspark.sql import SQLContext
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql import Row
from pyspark.sql.types import StringType

In [71]:
spark = SparkSession.Builder().appName("RezoJDM-SDS").getOrCreate()
sc = spark.sparkContext

jdmDUMP = sc.textFile("/content/JDM-LEXICALNET-FR/09032019-LEXICALNET-JEUXDEMOTS-FR-NOHTML-UTF8.txt")
# jdmDUMP = sc.textFile("/content/09032019-Template.txt")

In [72]:
jdmNodes = jdmDUMP.filter(lambda x: x[:4] == "eid=")

jdmNodes = jdmNodes.map(lambda x: 
                        Row(
                                eid = int(re.findall("eid=(\d+)\|n=", x)[0]) ,
                                n = re.findall("n=\"(.+)\"\|t=", x)[0] ,
                                t = int(re.findall("t=(-?\d+)\|w=", x)[0]) ,
                                w = int(re.findall("w=(-?\d+)", x)[0])
                            )
                  )

# only type 1 and 2 should be kept
jdmNodes = jdmNodes.filter(lambda x: (x["t"] == 1) | (x["t"] == 2))

# node whose text starts and ends with equal (“=”) are not french, don’t keep them
jdmNodes = jdmNodes.filter(lambda x: (~((x["n"][0] == "=") & (x["n"][-1] == "="))))

# filter the weights lesser than M(>50)
jdmNodes = jdmNodes.filter(lambda x: x["w"] > 50)

dfNodes = jdmNodes.toDF()

jdmNodes.count()

73106

In [73]:
jdmRelations = jdmDUMP.filter(lambda x: x[:4] == "rid=")

jdmRelations = jdmRelations.map(lambda x: 
                                    Row(
                                            rid = int(re.findall("rid=(\d+)\|n1=", x)[0]) ,
                                            n1 = int(re.findall("n1=(\d+)\|n2=", x)[0]) ,
                                            n2 = int(re.findall("n2=(-?\d+)\|t=", x)[0]) ,
                                            t = int(re.findall("t=(-?\d+)\|w=", x)[0]) ,
                                            w = int(re.findall("w=(-?\d+)", x)[0])
                                        )
                            )
# only type 1 and 2 should be kept
jdmRelations = jdmRelations.filter(lambda x: x["w"] > 50)

# keep all nodes except { 12, 18, 29, 33, 36, 45, 46, 47, 48, 1000, 1001, 1002, 444, 128, 200}
black_list_relation_ids = [12, 18, 29, 33, 36, 45, 46, 47, 48, 1000, 1001, 1002, 444, 128, 200]
jdmRelations = jdmRelations.filter(lambda x: x["t"] not in black_list_relation_ids)

# edges might refer to non-existing node, don’t keep those edges
existing_node_ids = list(dfNodes.toPandas()["eid"])
jdmRelations = jdmRelations.filter(lambda x: (x["n1"] in existing_node_ids) & (x["n2"] in existing_node_ids))

jdmRelations.count()

1512986

In [74]:
dfNodes = jdmNodes.toDF()
dfNodes = dfNodes.toPandas()

dfRelations = jdmRelations.toDF()
dfRelations = dfRelations.toPandas()

In [75]:
dfNodes.to_csv("nodes.csv", index=False)
dfRelations.to_csv("relations.csv", index=False)

In [120]:
dfNodes

            eid                n  t    w
0             1         vraiment  1  144
1             4       Conscience  1   52
2             6         provenir  1   52
3             8        traversée  1  158
4            12      discréditer  1   76
...         ...              ... ..  ...
73101  11151763        gros coup  1   52
73102  11172658      oeuf>140176  1   72
73103  11303561     opéra ballet  1   56
73104  11438901      être vautré  1   52
73105  11932897  café sans sucre  1   52

[73106 rows x 4 columns]

In [79]:
dfRelations

               rid      n1      n2   t    w
0                1   70226  132763   0   60
1                2   70226   55756   0   60
2                3   70226   73274   0   60
3                4   82745   95245   0  150
4                5  109319   33319   0   60
...            ...     ...     ...  ..  ...
1512981  338665982   68439   21301  24   63
1512982  338665983   21301   68439  13   60
1512983  338665988  396247   21301  24   58
1512984  338665989   21301  396247  13   55
1512985  338693573  136786   79513   8   70

[1512986 rows x 5 columns]

In [76]:
from google.colab import files

files.download("nodes.csv")
files.download("relations.csv")

In [105]:
nodes_out_degree = {}
nodes_in_degree = {}
nodes_degree = {}

for _, row in dfRelations.iterrows():
    
    if row.n1 in nodes_out_degree:
        nodes_out_degree[row.n1]+=1
    else:
        nodes_out_degree[row.n1]=1


    if row.n2 in nodes_in_degree:
        nodes_in_degree[row.n2]+=1
    else:
        nodes_in_degree[row.n2]=1


    if row.n1 in nodes_degree:
        nodes_degree[row.n1]+=1
    else:
        nodes_degree[row.n1]=1


    if row.n2 in nodes_degree:
        nodes_degree[row.n2]+=1
    else:
        nodes_degree[row.n2]=1

In [121]:
nodes_degree

{70226: 24,
 132763: 107,
 55756: 398,
 73274: 9,
 82745: 82,
 95245: 1187,
 109319: 32,
 33319: 54,
 32912: 77,
 102633: 681,
 97688: 22,
 136060: 15,
 131749: 32,
 123796: 16,
 30539: 13,
 45844: 225,
 64840: 11,
 130400: 2059,
 35444: 14,
 33187: 43,
 1453: 61,
 35841: 802,
 79684: 586,
 122384: 57,
 96889: 7,
 97756: 1013,
 49175: 147,
 63235: 1933,
 68299: 3,
 56280: 390,
 67400: 35,
 17559: 6343,
 12887: 122,
 71348: 414,
 136472: 246,
 11849: 120,
 129498: 97,
 7766: 103,
 2808: 66,
 36222: 193,
 29592: 3605,
 136729: 5,
 58324: 8,
 30030: 765,
 136733: 11,
 23519: 39,
 79239: 109,
 122704: 251,
 115865: 529,
 61092: 73,
 71578: 791,
 36899: 459,
 90075: 843,
 60829: 349,
 52747: 3,
 112601: 27,
 84773: 34,
 28947: 7,
 68307: 43,
 3695: 687,
 55593: 7,
 26846: 181,
 61147: 475,
 43583: 48,
 49345: 24,
 74888: 17,
 95280: 135,
 114738: 392,
 6334: 127,
 61686: 125,
 127337: 70,
 23705: 19,
 118876: 251,
 5978: 7,
 107477: 655,
 18229: 3,
 68255: 65,
 131321: 60,
 136736: 70,
 6974: 8,
 12099: 114,
 61490: 5286,
 29107: 67,
 5213: 79,
 64238: 774,
 88572: 8,
 136731: 12,
 112724: 107,
 20528: 199,
 102671: 104,
 123040: 486,
 31641: 772,
 47625: 30,
 73890: 973,
 34970: 332,
 113426: 28,
 76271: 74,
 125029: 182,
 6946: 270,
 32610: 610,
 39533: 46,
 123492: 208,
 39995: 6,
 108673: 371,
 102711: 44,
 84817: 77,
 86716: 10,
 115386: 199,
 32040: 27,
 112953: 195,
 31312: 69,
 1290: 100,
 25135: 183,
 116646: 29,
 106797: 379,
 3473: 98,
 117152: 321,
 74783: 44,
 25326: 98,
 67687: 6,
 9416: 17,
 9802: 13,
 87797: 30,
 96387: 638,
 103365: 457,
 120546: 73,
 42719: 154,
 1055: 327,
 44155: 174,
 116341: 47,
 66970: 463,
 136730: 1,
 43649: 7,
 130808: 515,
 50346: 42,
 34659: 77,
 15206: 8,
 87286: 1050,
 125875: 10,
 65012: 1678,
 100835: 59,
 32420: 50,
 83011: 74,
 65938: 134,
 5678: 3,
 32403: 238,
 78299: 24,
 102647: 12,
 75003: 541,
 48123: 4,
 52456: 16,
 5299: 32,
 128438: 23,
 20564: 899,
 57933: 819,
 89926: 740,
 13444: 154,
 97173: 730,
 22669: 30,
 136597: 156,
 20910: 222,
 68900: 49,
 103148: 122,
 46647: 26,
 86306: 776,
 57484: 7,
 2320: 26,
 105890: 30,
 40742: 91,
 58299: 6,
 18746: 236,
 118047: 59,
 75377: 422,
 5263: 24,
 13200: 88,
 74259: 121,
 136732: 5,
 72731: 558,
 41368: 338,
 81145: 231,
 49803: 790,
 17690: 28,
 50005: 3,
 62899: 16,
 102206: 2285,
 62257: 10,
 7943: 751,
 122864: 1167,
 8915: 55,
 136560: 19,
 85341: 18,
 103499: 52,
 48599: 57,
 34741: 27,
 83208: 388,
 103546: 3,
 20727: 16,
 73063: 5,
 65808: 319,
 96851: 894,
 100445: 583,
 130281: 41,
 32368: 65,
 69182: 561,
 39199: 224,
 56509: 119,
 23274: 11,
 73888: 156,
 49477: 40,
 102812: 514,
 125918: 126,
 68442: 82,
 112939: 3,
 13626: 43,
 23008: 26,
 9090: 57,
 135600: 19,
 116051: 114,
 72477: 161,
 100640: 1193,
 71169: 3,
 114118: 20,
 56865: 1211,
 38141: 57,
 67730: 160,
 52105: 53,
 74860: 8107,
 22009: 40,
 30051: 21,
 89987: 84,
 16747: 404,
 116088: 13,
 83203: 17,
 1587: 9,
 112487: 4,
 46728: 870,
 25859: 88,
 22335: 100,
 16015: 5,
 5602: 12,
 3318: 45,
 101621: 146,
 23053: 139,
 43208: 53,
 93195: 39,
 19356: 754,
 36124: 196,
 78445: 354,
 27692: 182,
 6226: 154,
 96005: 9,
 99776: 21,
 68295: 210,
 44947: 90,
 40531: 197,
 121359: 182,
 49556: 22,
 85711: 11,
 106975: 10,
 124184: 35,
 19945: 36,
 86043: 41,
 135679: 121,
 94854: 33,
 84162: 48,
 24222: 22,
 50195: 248,
 92058: 145,
 46363: 50,
 96323: 95,
 25179: 80,
 73114: 226,
 82844: 108,
 136752: 2,
 103028: 314,
 30364: 21,
 92878: 317,
 90339: 63,
 115456: 27,
 36193: 5,
 101650: 56,
 88020: 8,
 30843: 1222,
 14347: 34,
 135627: 6,
 53821: 89,
 71100: 7,
 45196: 15,
 14358: 187,
 84223: 241,
 110920: 4,
 6890: 1375,
 100534: 273,
 76160: 119,
 128641: 50,
 53322: 172,
 27604: 156,
 101647: 6,
 48539: 79,
 32528: 215,
 1870: 200,
 34939: 86,
 73963: 396,
 61475: 72,
 123408: 305,
 42778: 1,
 132717: 15,
 43286: 194,
 25084: 23,
 73844: 5,
 7530: 53,
 53555: 21,
 94650: 135,
 130949: 239,
 125360: 31,
 59682: 1,
 76804: 28,
 114015: 237,
 105689: 32,
 100234: 22,
 29476: 74,
 88629: 65,
 39091: 28,
 28741: 13,
 128791: 127,
 81389: 80,
 73427: 533,
 37849: 42,
 75807: 89,
 85501: 153,
 45216: 377,
 47468: 173,
 74759: 23,
 94787: 64,
 8352: 183,
 36089: 11,
 61061: 169,
 68128: 233,
 52550: 8,
 48719: 22,
 61016: 635,
 42109: 568,
 10564: 244,
 34604: 131,
 59303: 215,
 119088: 23,
 26976: 692,
 73956: 79,
 61185: 313,
 91029: 79,
 122439: 276,
 134536: 640,
 30700: 199,
 84983: 181,
 10113: 13,
 25705: 767,
 736: 19,
 64568: 206,
 16931: 112,
 110724: 77,
 81373: 153,
 92283: 32,
 5051: 168,
 130812: 61,
 106553: 88,
 44654: 371,
 89717: 10,
 34529: 66,
 75338: 3,
 5707: 112,
 123990: 3,
 7049: 162,
 6624: 15,
 93583: 200,
 84146: 6,
 30318: 58,
 11357: 10,
 85519: 77,
 123090: 172,
 92471: 273,
 122662: 141,
 13555: 62,
 19764: 673,
 89874: 56,
 70527: 1119,
 103353: 441,
 100905: 19,
 99887: 9,
 3171: 218,
 44663: 253,
 28205: 6,
 32804: 38,
 40355: 315,
 119768: 86,
 77735: 427,
 42313: 326,
 101481: 10,
 14411: 9,
 52704: 205,
 24670: 363,
 101938: 242,
 130164: 1287,
 56365: 200,
 7190: 210,
 61936: 386,
 59555: 184,
 11589: 10,
 110788: 17,
 36285: 79,
 16449: 35,
 122852: 634,
 35345: 161,
 33524: 101,
 120511: 154,
 134891: 98,
 2653: 10,
 32186: 86,
 53541: 692,
 114796: 50,
 135329: 299,
 37052: 33,
 101913: 431,
 82263: 32,
 10322: 186,
 133915: 21,
 125045: 35,
 13712: 564,
 33641: 7,
 18503: 32,
 32287: 45,
 84095: 11,
 80635: 87,
 54490: 314,
 27890: 110,
 127661: 11,
 128873: 12,
 43253: 701,
 99394: 288,
 108463: 362,
 112773: 102,
 44886: 242,
 74582: 11,
 104299: 18,
 120609: 10,
 91358: 425,
 45179: 1762,
 100988: 211,
 63018: 251,
 10879: 647,
 111006: 80,
 80315: 57,
 66566: 33,
 127852: 60,
 34395: 83,
 65000: 64,
 54025: 147,
 54429: 20,
 94426: 1,
 87987: 1517,
 113669: 297,
 125191: 18,
 10822: 4,
 85729: 1,
 109785: 854,
 108646: 11,
 46556: 10,
 38867: 337,
 59900: 63,
 18272: 262,
 29105: 143,
 26638: 439,
 9549: 429,
 120673: 134,
 56565: 16,
 107120: 284,
 117078: 67,
 8673: 85,
 27268: 425,
 2450: 2,
 117537: 28,
 27120: 604,
 59071: 744,
 76222: 17,
 136765: 29,
 126860: 16,
 111358: 149,
 127899: 123,
 54735: 21,
 8586: 157,
 9224: 6,
 65966: 481,
 130331: 22,
 52908: 35,
 129417: 294,
 68159: 115,
 91046: 504,
 20300: 3,
 73119: 51,
 28879: 81,
 66826: 11,
 106722: 90,
 120364: 81,
 9864: 655,
 33892: 53,
 129333: 7,
 54613: 95,
 60703: 54,
 35798: 669,
 117423: 648,
 110910: 527,
 35245: 31,
 31953: 122,
 54090: 185,
 119518: 7,
 17968: 347,
 107367: 9,
 84266: 210,
 123432: 4,
 33644: 77,
 107627: 11,
 26128: 27,
 19122: 38,
 2026: 504,
 12105: 288,
 71467: 455,
 32751: 8,
 87887: 563,
 12431: 55,
 132350: 693,
 29735: 221,
 97538: 168,
 36327: 834,
 89591: 711,
 20965: 855,
 89487: 113,
 104824: 86,
 16768: 16,
 48981: 68,
 81680: 98,
 57720: 83,
 13861: 825,
 267: 71,
 41224: 144,
 19790: 55,
 49428: 13,
 98103: 9,
 11228: 105,
 115975: 5,
 14235: 124,
 14723: 46,
 13673: 9,
 1530: 269,
 23777: 3,
 116899: 27,
 21254: 105,
 58818: 32,
 26923: 79,
 30106: 215,
 119244: 87,
 79356: 7,
 35588: 107,
 34898: 911,
 58700: 13,
 26525: 26,
 100891: 64,
 111776: 393,
 133345: 142,
 106081: 308,
 59933: 121,
 9548: 43,
 46209: 2,
 63736: 147,
 65447: 232,
 12941: 563,
 60095: 68,
 135591: 459,
 134234: 72,
 39625: 8,
 32645: 70,
 35999: 262,
 110236: 315,
 117587: 14,
 5498: 83,
 32367: 118,
 117276: 285,
 2835: 15,
 2680: 835,
 6546: 204,
 150: 1081,
 113325: 193,
 61223: 193,
 72246: 14,
 1123: 40,
 105503: 134,
 52980: 147,
 1737: 20,
 68620: 368,
 103457: 220,
 123745: 1624,
 136784: 41,
 13090: 195,
 110970: 39,
 39575: 204,
 46297: 32,
 43786: 50,
 145941: 2552,
 113547: 1064,
 105202: 24,
 40056: 1764,
 12130: 100,
 136783: 36,
 93245: 135,
 11439: 284,
 116212: 173,
 108042: 13,
 126963: 201,
 41603: 63,
 85696: 61,
 109333: 190,
 118538: 2211,
 103518: 425,
 88036: 32,
 118975: 88,
 141977: 488,
 116746: 169,
 34467: 70,
 119135: 38,
 23919: 208,
 103389: 622,
 11191: 342,
 9380: 35,
 144916: 891,
 120465: 18,
 41870: 166,
 136775: 71,
 73622: 143,
 73981: 98,
 144129: 157,
 64181: 141,
 133949: 187,
 35712: 313,
 62664: 151,
 43504: 742,
 11380: 166,
 122393: 482,
 24522: 543,
 2715: 37,
 75277: 13,
 37370: 50,
 85860: 41,
 52255: 1129,
 136507: 2118,
 138874: 365,
 143607: 637,
 67543: 7,
 88839: 180,
 59842: 37,
 146367: 1142,
 86700: 66,
 5074: 108,
 37646: 198,
 36177: 61,
 31678: 8,
 26477: 506,
 14850: 207,
 48529: 38,
 115796: 92,
 61921: 306,
 106981: 119,
 34503: 470,
 23004: 15,
 7608: 120,
 10881: 407,
 37044: 147,
 18571: 268,
 928: 14,
 74558: 608,
 98488: 23,
 25008: 623,
 86356: 938,
 113386: 65,
 87251: 24,
 120100: 40,
 129313: 4,
 13001: 68,
 26510: 12,
 61281: 223,
 110107: 14,
 200: 28,
 101702: 17,
 6176: 13,
 145792: 580,
 136788: 138,
 48211: 31,
 58347: 28,
 69725: 33,
 63462: 207,
 50729: 80,
 39755: 19,
 105655: 77,
 122556: 39,
 81251: 133,
 77184: 86,
 146033: 400,
 32169: 15,
 59574: 67,
 58659: 40,
 86490: 162,
 113016: 120,
 116032: 497,
 58646: 144,
 12882: 12,
 141457: 280,
 103082: 284,
 68883: 52,
 50567: 404,
 100222: 393,
 22310: 4,
 134794: 21,
 66592: 15,
 81434: 49,
 123735: 87,
 66909: 420,
 143377: 24,
 31748: 8,
 93941: 258,
 95060: 74,
 19150: 533,
 64887: 123,
 102641: 452,
 23339: 127,
 135076: 20,
 35352: 277,
 146774: 91,
 10576: 931,
 33206: 25,
 32071: 351,
 58906: 134,
 27918: 72,
 53115: 11,
 55600: 137,
 120929: 10,
 146724: 5,
 140238: 174,
 136779: 14,
 35778: 74,
 95430: 65,
 100402: 231,
 144936: 453,
 23411: 30,
 135982: 94,
 15763: 76,
 26979: 164,
 39031: 601,
 144846: 1286,
 40542: 12,
 53320: 179,
 125964: 161,
 47123: 236,
 119973: 206,
 102195: 9,
 136786: 3338,
 4455: 1061,
 40545: 88,
 19991: 67,
 128782: 541,
 144718: 636,
 38710: 663,
 142787: 1143,
 12502: 1478,
 22885: 479,
 54234: 307,
 112621: 257,
 106970: 315,
 146768: 33,
 29472: 72,
 136785: 383,
 132034: 63,
 63509: 482,
 35167: 180,
 91580: 3,
 95003: 24,
 32194: 8,
 16110: 898,
 136762: 20,
 823: 19,
 136778: 31,
 49116: 190,
 66141: 51,
 131363: 3,
 48943: 84,
 74736: 651,
 25599: 240,
 63763: 61,
 626: 7099,
 139461: 32,
 124094: 1963,
 21274: 30,
 52673: 157,
 97807: 70,
 14500: 153,
 35579: 87,
 66131: 22,
 135985: 237,
 87796: 9,
 41063: 81,
 15127: 213,
 75933: 50,
 126405: 272,
 142761: 18,
 39903: 35,
 39816: 238,
 146781: 156,
 14265: 67,
 130190: 14,
 78981: 30,
 141609: 14,
 12060: 46,
 16392: 197,
 60: 667,
 68971: 5,
 5054: 26,
 71926: 1032,
 133393: 204,
 54956: 228,
 129051: 19,
 71: 18,
 52359: 6,
 143112: 44,
 95665: 78,
 105822: 81,
 73715: 100,
 146763: 16,
 146802: 36,
 139388: 260,
 140569: 74,
 95659: 279,
 52731: 8,
 32132: 544,
 94555: 63,
 116800: 37,
 144681: 6046,
 145035: 207,
 32202: 142,
 116567: 69,
 37376: 68,
 146803: 270,
 20048: 38,
 88096: 675,
 57592: 281,
 108321: 63,
 139354: 33,
 143712: 653,
 107150: 1120,
 146105: 1238,
 100370: 267,
 46897: 6,
 137841: 99,
 121678: 689,
 132633: 15,
 52497: 166,
 31457: 25,
 48071: 36,
 30171: 706,
 52051: 96,
 67196: 131,
 112428: 38,
 25437: 271,
 3674: 887,
 3343: 370,
 22243: 1577,
 146780: 71,
 68256: 510,
 146807: 33,
 124068: 122,
 140176: 1596,
 55222: 1020,
 7769: 497,
 32625: 83,
 16930: 244,
 123288: 92,
 23241: 111,
 132347: 207,
 146798: 94,
 24742: 975,
 146767: 305,
 30397: 217,
 146808: 18,
 24808: 28,
 146809: 23,
 19193: 15,
 26403: 134,
 42196: 246,
 136787: 23,
 138187: 241,
 146810: 38,
 106664: 57,
 105452: 68,
 112905: 463,
 146766: 28,
 112758: 43,
 7795: 159,
 125545: 7,
 111921: 251,
 16029: 22,
 63471: 426,
 6211: 100,
 41417: 717,
 134690: 6,
 52119: 823,
 37768: 102,
 32303: 339,
 141387: 428,
 122320: 82,
 80449: 31,
 146793: 35,
 4157: 92,
 13261: 21,
 92836: 190,
 80574: 101,
 3801: 60,
 115805: 379,
 72805: 358,
 49207: 1012,
 94116: 111,
 77008: 708,
 82271: 39,
 3530: 365,
 73527: 63,
 139303: 263,
 79333: 145,
 34080: 425,
 39362: 60,
 103677: 17,
 29784: 14,
 140593: 131,
 70465: 140,
 82231: 449,
 117789: 179,
 146782: 117,
 55135: 327,
 59550: 158,
 36204: 362,
 66808: 232,
 68926: 67,
 83202: 32,
 146792: 141,
 3721: 5,
 94119: 39,
 131068: 25,
 28805: 49,
 101051: 15,
 82414: 245,
 49928: 326,
 120791: 107,
 132037: 267,
 74978: 66,
 16644: 328,
 112357: 187,
 61840: 4,
 107179: 263,
 122956: 571,
 43839: 346,
 81219: 8,
 131009: 117,
 75256: 26,
 41971: 238,
 64070: 26,
 146821: 116,
 82879: 10,
 104563: 82,
 12831: 837,
 101780: 31,
 86315: 109,
 46275: 73,
 146357: 1285,
 146822: 60,
 146823: 37,
 112029: 12,
 118908: 369,
 56413: 89,
 122865: 148,
 140318: 740,
 78456: 13,
 94596: 254,
 117170: 11,
 51121: 104,
 90513: 10,
 79014: 34,
 46844: 111,
 24391: 10,
 78365: 460,
 146799: 43,
 101895: 103,
 146261: 507,
 146813: 15,
 146825: 15,
 39448: 442,
 37298: 2084,
 120759: 113,
 ...}

In [109]:
len(dfRelations["t"].unique())

113

In [116]:
values=[]
keys=[]

for key, value in nodes_degree.items():
    values.append(value)
    keys.append(key)
    if value == 15818:
        print(key)

116477

In [117]:
import numpy as np
min(items), max(items), np.mean(items)

(1, 15818, 42.73066440725835)

In [119]:
dfNodes[dfNodes["eid"]==116477]

          eid         n  t     w
35977  116477  personne  1  9834